export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";
export const CLEAR_CARTORDER = "CLEAR_CARTORDER";
export const GET_SECTION_PRODUCTS = "GET_SECTION_PRODUCTS";
export const SET_WIDTH_FILTER = "SET_WIDTH_FILTER";
